apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress
  labels:
    app: progress
    service: progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
      service: progress
  template:
    metadata:
      labels:
        app: progress
        service: progress
    spec:
      volumes:
      - name: progress-volume
        persistentVolumeClaim:
          claimName: progress
      containers:
      - name: progress-container
        image: hhana982/progress:1.<version>
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "/"
          name: progress-volume
        env: 