apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress
  labels:
    app: progress
    service: progress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress
      service: progress
  template:
    metadata:
      labels:
        app: progress
        service: progress
    spec:
      containers:
      - name: progress-container
        image: hhana982/progress:1.<version>
        ports:
        - containerPort: 5000
        env: 
        - name: DB_HOST
          value: "progress-db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "rootpassword"
        - name: DB_PORT
          value: "3306"